org: isislin
app: line-bot
service: line-bot
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  environment:
    CHANNEL_SECRET: ${env:CHANNEL_SECRET}
    CHANNEL_ACCESS_TOKEN: ${env:CHANNEL_ACCESS_TOKEN}


functions:
  function1:
    handler: handler.webhook
    events:
      - http:
          path: /webhook
          method: post
  
package:
  patterns:
    - image/**
    - message-pai/**
    - messages/**
    - config/**

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
